USE [WEDOCO]
GO

/****** Object:  View [dbo].[v_ReceiptBill]    Script Date: 02-Mar-20 08:57:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[v_ReceiptBill]
AS
SELECT                        
                      
 ( case  WHEN dbo.HEAD_PASTE.BILLID = '' THEN dbo.HEAD_PASTE.TAXID ELSE  dbo.HEAD_PASTE.BILLID END) as RECID
,(dbo.DETAIL_PASTE.CUSTID)AS BILLID,(dbo.HEAD_PASTE.ARID) AS CUSID, dbo.HEAD_PASTE.DATEOPEN, dbo.HEAD_PASTE.GROUPNAME, dbo.HEAD_PASTE.ADDNAME, 
                      dbo.HEAD_PASTE.ADDDETAIL, dbo.HEAD_PASTE.TERM, dbo.HEAD_PASTE.COMMENT, dbo.HEAD_PASTE.DATECHQ, dbo.HEAD_PASTE.TAXID, dbo.HEAD_PASTE.ID, 
                      dbo.HEAD_PASTE.VPOST, dbo.HEAD_PASTE.TTYPE, dbo.HEAD_PASTE.COMMENT2, dbo.HEAD_PASTE.COMMENT3, dbo.HEAD_PASTE.COMMENT4, 
                      dbo.HEAD_PASTE.COMMENT5,  dbo.DETAIL_PASTE.INVID, dbo.DETAIL_PASTE.POID, dbo.DETAIL_PASTE.DATEINV, 
                      dbo.DETAIL_PASTE.DUEDATE, dbo.DETAIL_PASTE.DESC1, dbo.DETAIL_PASTE.VAT, dbo.DETAIL_PASTE.AMOUNTVAT, dbo.DETAIL_PASTE.AMOUNT, 
                      dbo.DETAIL_PASTE.AMOUNT1, dbo.DETAIL_PASTE.AMOUNTDUE, dbo.DETAIL_PASTE.CUSTID, dbo.DETAIL_PASTE.CUSNAME, 
                      dbo.DETAIL_PASTE.DISCOUNT
            
FROM         dbo.HEAD_PASTE LEFT OUTER JOIN
                      dbo.DETAIL_PASTE ON dbo.HEAD_PASTE.BILLID = dbo.DETAIL_PASTE.BILLID AND   dbo.HEAD_PASTE.TAXID =  dbo.DETAIL_PASTE.TAXID
WHERE     dbo.HEAD_PASTE.TTYPE = 1

Union All

SELECT   ( case  WHEN dbo.HEAD_PASTE.BILLID = '' THEN dbo.HEAD_PASTE.TAXID ELSE  dbo.HEAD_PASTE.BILLID END) as  RECID
,(dbo.HEAD_PASTE.ARID) AS BILLID,(dbo.DETAIL_PASTE.CUSTID) AS CUSID,dbo.HEAD_PASTE.DATEOPEN, dbo.HEAD_PASTE.GROUPNAME, dbo.HEAD_PASTE.ADDNAME, 
                      dbo.HEAD_PASTE.ADDDETAIL, dbo.HEAD_PASTE.TERM, dbo.HEAD_PASTE.COMMENT, dbo.HEAD_PASTE.DATECHQ, dbo.HEAD_PASTE.TAXID, dbo.HEAD_PASTE.ID, 
                      dbo.HEAD_PASTE.VPOST, dbo.HEAD_PASTE.TTYPE, dbo.HEAD_PASTE.COMMENT2, dbo.HEAD_PASTE.COMMENT3, dbo.HEAD_PASTE.COMMENT4, 
                      dbo.HEAD_PASTE.COMMENT5,  dbo.DETAIL_PASTE.INVID, dbo.DETAIL_PASTE.POID, dbo.DETAIL_PASTE.DATEINV, 
                      dbo.DETAIL_PASTE.DUEDATE, dbo.DETAIL_PASTE.DESC1, dbo.DETAIL_PASTE.VAT, dbo.DETAIL_PASTE.AMOUNTVAT, dbo.DETAIL_PASTE.AMOUNT, 
                      dbo.DETAIL_PASTE.AMOUNT1, dbo.DETAIL_PASTE.AMOUNTDUE, dbo.DETAIL_PASTE.CUSTID, dbo.DETAIL_PASTE.CUSNAME, 
                      dbo.DETAIL_PASTE.DISCOUNT
FROM         dbo.HEAD_PASTE LEFT OUTER JOIN
                      dbo.DETAIL_PASTE ON dbo.HEAD_PASTE.BILLID = dbo.DETAIL_PASTE.BILLID AND   dbo.HEAD_PASTE.TAXID =  dbo.DETAIL_PASTE.TAXID
WHERE     dbo.HEAD_PASTE.TTYPE = 0


GO


